services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Smichaelsen\MelonImages\Command\CreateNeededCroppingsCommand:
    tags:
      - name: 'console.command'
        command: 'melon-images:createcoppings'

